name            = "ajar-api"
main            = "workers/api/src/index.ts"
compatibility_date  = "2024-12-01"
compatibility_flags = ["nodejs_compat"]

# ── KV Namespaces ─────────────────────────────────────────────────────────────

[[kv_namespaces]]
binding = "SESSIONS"
id      = "074d45fbd4a143e585749523f3e15bd0"

# ── D1 ─────────────────────────────────────────────────────────────────────────

[[d1_databases]]
binding       = "DB"
database_name = "ajar-db"
database_id   = "cb0e4b80-9cbd-4f9d-975d-728d9b0e171c"

# ── Vars ───────────────────────────────────────────────────────────────────────

[vars]
API_WORKER_URL = "https://ajar-api.teycircoder10.workers.dev"
